# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calendar.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63\x61lendar.proto\x12\x0e\x63\x61lendar_proto\x1a\x1fgoogle/protobuf/timestamp.proto\"Z\n\x07\x41\x64\x64Note\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04note\x18\x02 \x01(\t\x12\x11\n\tdate_note\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x61te_remind\x18\x04 \x01(\t\x12\r\n\x05\x65mail\x18\x05 \x01(\t\"\x18\n\x06Status\x12\x0e\n\x06status\x18\x01 \x01(\x08\x32Q\n\x0f\x43\x61lendarService\x12>\n\x0bRecieveData\x12\x17.calendar_proto.AddNote\x1a\x16.calendar_proto.Statusb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calendar_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ADDNOTE._serialized_start=67
  _ADDNOTE._serialized_end=157
  _STATUS._serialized_start=159
  _STATUS._serialized_end=183
  _CALENDARSERVICE._serialized_start=185
  _CALENDARSERVICE._serialized_end=266
# @@protoc_insertion_point(module_scope)
