# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gRPCError/error.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15gRPCError/error.proto\x12\x0b\x65rror_proto\"$\n\x08\x41\x64\x64\x45rror\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04\x66lag\x18\x02 \x01(\x08\"\x18\n\x06Status\x12\x0e\n\x06status\x18\x01 \x01(\x08\x32\x46\n\x0b\x45rrorMethod\x12\x37\n\tSendErrot\x12\x15.error_proto.AddError\x1a\x13.error_proto.Statusb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gRPCError.error_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ADDERROR._serialized_start=38
  _ADDERROR._serialized_end=74
  _STATUS._serialized_start=76
  _STATUS._serialized_end=100
  _ERRORMETHOD._serialized_start=102
  _ERRORMETHOD._serialized_end=172
# @@protoc_insertion_point(module_scope)
